name: android_battery_optimizations
description: You can check battery optimization status and launch permission dialog. This plugin does not cover "manufacturer battery optimizations" checks yet. Planning to add this feature soon.
version: 0.0.2
homepage: https://github.com/lancehuang245/android_battery_optimizations

environment:
  sdk: ^3.10.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 

flutter:
  plugin:
    platforms:
      android:
        package: com.example.android_battery_optimizations
        pluginClass: AndroidBatteryOptimizationsPlugin
